### ISSUE TITLE
SAASH installation running into trouble with Numpy version

### ISSUE THREAD

**Issue by naren48** [onehalfatsquared/SAASH#12]
I get the following issue when I try running the installation as instructed :
error: numpy 1.24.1 is installed but numpy<1.23.0,>=1.16.5 is required by {'scipy'}

I'm not sure if this introduces any issues in the installation. I can circumvent the problem by installing it through a virtual environment that has an earlier version of NumPy. But is that ok ? Will I always have to run the stuff I need on a virtual environment ? Can this issue be fixed so that the installation routine ( and the analysis routines called from this Library ) run with the latest version of NumPy ?

**Comment by onehalfatsquared** [comment]
This was handled offline. 

Solutions were to either install the library in a virtual environment, or attempt to use the second installation method on the Code page with the --force-reinstall flag.
